### ISSUE TITLE
Probleme sur la fonction de conversion degree / cardinal

### ISSUE THREAD

**Issue by vlad-0** [Davidlouiz/balise#1]
Exemple de ma fonction pour le text2speech des balises en bash...

compass=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW )
ix=$(bc -l <<< "scale=2; $directVentMoy / (360 / 16)")
index=$(echo $ix | awk '{printf("%d\n",$1 + 0.5)}')
direction="${compass[$index%16]}"

**Comment by vlad-0** [comment]
> Exemple de ma fonction pour le text2speech des balises en bash...
> 
> compass=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW )
> ix=$(bc -l <<< "scale=2; $directVentMoy / (360 / 16)")
> index=$(echo $ix | awk '{printf("%d\n",$1 + 0.5)}')
> direction="${compass[$index%16]}"

En gros, j'ajoute 0.5 car il n'y a pas de fonction d'arrondi en bash sauf installer des trucs...
de ton coté tu utilises floor, mais il me semble que ça arrondi à l’inférieur, d'où le bug...

**Comment by Davidlouiz** [comment]
Avec round() à la place de floor() ça a l'aire de mieux marcher.
